# Generated by Django 3.2.14 on 2022-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_gamemodel_playermodel_tournamentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='handicap',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Фора'),
        ),
    ]
