# Generated by Django 3.2.14 on 2022-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_gamemodel_handicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='tournaments',
            field=models.ManyToManyField(related_name='tournament_players', to='tournaments.TournamentModel'),
        ),
    ]
