# Generated by Django 3.2.14 on 2022-09-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentmodel_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tournaments_in_pc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество турниров в карточке игрока')),
                ('number_of_opponents_in_pc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество отображаемых оппонентов в карточке игрока')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
